export const errorMessages = {
  SERVER_ERROR: "SERVER ERROR",
  DOESNOT_EXIST_TODO: "TODO DOES NOT EXIST",
  TODO_INVALID: "TODO IS INVALID",
  SEARCH_ERROR: "SEARCH ERROR",
  REFRESH_TOKEN_GENERATING_ERROR: "ERROR GENERATING TOKENS",
  REFRESH_TOKEN_INVALID: "INVALID REFRESH TOKEN",
  ACCESS_TOKEN_INVALID: "INVALID ACCESS TOKEN",
  NOT_EXIST_ACCESS_TOKEN: "TOKEN DOES NOT EXIST",
  TOKENS_GENERATING_ERROR: "Error generating tokens",
  EXIST_USER: "USER ALREADY EXISTS",
  NOT_EXIST_USER: "USER DOES NOT EXIST",
  INVALID_PASSWORD: "INVALID PASSWORD",
  INVALID_EMAIL: "INVALID EMAIL",
  NOT_EXIST_WORKSPACE: "WORK SPACE DOES NOT EXIST",
  WORKSPACE_INVALID: "WORK SPACE IS INVALID",
  NOT_EXIST_SECTION: "SECTION DOES NOT EXIST",
  USER_HAS_NO_WORKSPACE: "USER HAS NO WORKSPACE",
};

export const errorTypes = {
  SERVER_ERROR: "001",
  AUTH_ERROR: "002",
  TODO_ERROR: "003",
  AUTH_MIDDLEWARE_ERROR: "004",
  SEARCH_ERROR: "005",
  REFRESH_TOKEN_ERROR: "006",
  WORKSPACE_ERROR: "007",
};
